services:
    keycloak:
        container_name: keycloak_web
        command:
            -   start-dev
        image: quay.io/keycloak/keycloak:26.0.7
        ports:
            -   8080:8080
        volumes:
            - kc_data:/var/lib/kc
        entrypoint: /opt/keycloak/bin/kc.sh
        environment:
            KEYCLOAK_ADMIN: admin
            KEYCLOAK_ADMIN_PASSWORD: admin
            KC_HTTP_PORT: 8080
            KC_HOSTNAME_URL: http://localhost:8080
            KC_HOSTNAME_ADMIN_URL: http://localhost:8080
            KC_LOG_LEVEL: info
            KC_HTTP_ENABLED: true
            KC_HEALTH_ENABLED: true
            KC_METRICS_ENABLED: true
            KC_HOSTNAME: localhost
            KC_DB: mysql
            KC_DB_URL: jdbc:mysql://mysql:3306/kc_db
            KC_DB_USERNAME: root
            KC_DB_PASSWORD: root



volumes:
    kc_data:
