server:
  port: 8888
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
        routes:
          - id : products_service
            uri : http://localhost:8081
            predicates:
              - Path=/products/**
          - id : stores_services
            uri : http://localhost:8082
            predicates:
              - Path=/store/**
          - id : stores_services
            uri : http://localhost:8080
            predicates:
              - Path=/api/users/**

#eureka:
#  client:
#    registerWithEureka: true
#    fetchRegistry: true
#    serviceUrl:
#      defaultZone: http://localhost:8761
#  instance:
#    hostname: localhost

